In [1]:
import requests
import pandas as pd
import numpy as np

## 1. Definindo cabeçalho da requisição

In [79]:
url = 'https://www.fundsexplorer.com.br/ranking'
headers = {
    'User-Agent': 
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36'
        ' (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36'
}

In [80]:
response = requests.get(url, headers=headers)
if response.status_code == 200:
    df = pd.read_html(response.content, encoding='utf-8')[0]

In [81]:
df.sort_values('Códigodo fundo', inplace=True)

In [82]:
df

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
137,ABCP11,Shoppings,"R$ 73,97",2654.0,"R$ 0,51","0,74%","1,27%","2,58%","0,00%","0,42%",...,"R$ 1.077.525.130,29","R$ 88,29",84.0,"0,44%","-0,05%","0,39%","1,48%","9,10%",NaN,1
129,AFCR11,Híbrido,"R$ 110,84",515.0,"R$ 1,55","1,40%","3,29%","5,94%","10,57%","1,10%",...,"R$ 121.528.154,28","R$ 102,36",108.0,NaN,NaN,NaN,NaN,NaN,NaN,0
29,AFOF11,Títulos e Val. Mob.,"R$ 106,75",5826.0,"R$ 8,76","8,76%","8,76%","8,76%","16,82%","2,92%",...,"R$ 39.305.966,92","R$ 107,06",100.0,NaN,NaN,NaN,NaN,NaN,NaN,0
126,AIEC11,Lajes Corporativas,"R$ 80,60",4416.0,"R$ 0,57","0,69%","1,97%","3,81%","0,00%","0,66%",...,"R$ 483.257.233,98","R$ 100,16",80.0,NaN,NaN,NaN,NaN,"0,00%",NaN,2
3,ALMI11,Lajes Corporativas,"R$ 1.145,00",176.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%",...,"R$ 229.163.662,27","R$ 2.061,25",56.0,NaN,NaN,NaN,NaN,"68,15%",NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49,XPML11,Shoppings,"R$ 107,75",44998.0,"R$ 0,40","0,38%","0,81%","1,95%","3,56%","0,27%",...,"R$ 2.001.282.055,70","R$ 109,91",98.0,NaN,NaN,NaN,NaN,"5,90%",NaN,13
71,XPPR11,Outros,"R$ 68,70",14574.0,"R$ 0,48","0,73%","2,19%","4,17%","8,88%","0,73%",...,"R$ 627.324.285,79","R$ 85,74",80.0,NaN,NaN,NaN,NaN,"47,00%",NaN,4
171,XPSF11,Outros,"R$ 93,69",15014.0,"R$ 0,75","0,80%","2,50%","4,81%","9,28%","0,83%",...,"R$ 401.337.388,51","R$ 92,68",101.0,NaN,NaN,NaN,NaN,NaN,NaN,0
2,XTED11,Lajes Corporativas,"R$ 6,85",3560.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%",...,"R$ 25.862.448,60","R$ 13,97",49.0,NaN,NaN,NaN,NaN,"0,00%","100,00%",1
133,YUFI11B,Residencial,NaN,NaN,"R$ 0,40","0,00%","0,00%","0,00%","0,00%","0,00%",...,"R$ 37.614.094,39","R$ 95,19",NaN,"0,18%","0,23%","0,41%","0,41%",NaN,NaN,0

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 244 entries, 137 to 133
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Códigodo fundo           244 non-null    object
 1   Setor                    243 non-null    object
 2   Preço Atual              237 non-null    object
 3   Liquidez Diária          237 non-null    float64
 4   Dividendo                244 non-null    object
 5   DividendYield            231 non-null    object
 6   DY (3M)Acumulado         231 non-null    object
 7   DY (6M)Acumulado         231 non-null    object
 8   DY (12M)Acumulado        231 non-null    object
 9   DY (3M)Média             231 non-null    object
 10  DY (6M)Média             231 non-null    object
 11  DY (12M)Média            231 non-null    object
 12  DY Ano                   220 non-null    object
 13  Variação Preço           231 non-null    object
 14  Rentab.Período           231 non-null    object
 15  Rentab.Acumulada         231 non-null    object
 16  PatrimônioLíq.           244 non-null    object
 17  VPA                      244 non-null    object
 18  P/VPA                    237 non-null    float64
 19  DYPatrimonial            56 non-null     object
 20  VariaçãoPatrimonial      56 non-null     object
 21  Rentab. Patr.no Período  56 non-null     object
 22  Rentab. Patr.Acumulada   56 non-null     object
 23  VacânciaFísica           118 non-null    object
 24  VacânciaFinanceira       26 non-null     object
 25  QuantidadeAtivos         244 non-null    int64
dtypes: float64(2), int64(1), object(23)
memory usage: 51.5+ KB

In [19]:
df.describe(include='all')

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
count,244,243,237,237.000000,244,231,231,231,231,231,...,244,244,237.0,56,56,56,56,118,26,244.000000
unique,242,9,226,NaN,126,101,150,162,145,100,...,242,236,NaN,44,49,48,52,73,16,NaN
top,RBBV11,Títulos e Val. Mob.,"R$ 100,00",NaN,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%",...,"R$ 126.592.088,63","R$ 100,94",NaN,"1,00%","0,03%","1,04%","3,30%","0,00%","0,00%",NaN
freq,3,74,3,NaN,14,20,22,44,75,22,...,3,3,NaN,4,5,3,3,40,11,NaN
mean,NaN,NaN,NaN,15667.303797,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,inf,NaN,NaN,NaN,NaN,NaN,NaN,3.340164
std,NaN,NaN,NaN,45499.605553,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.930969
min,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-155.0,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
25%,NaN,NaN,NaN,314.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,84.0,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
50%,NaN,NaN,NaN,3414.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,96.0,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
75%,NaN,NaN,NaN,14346.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,102.0,NaN,NaN,NaN,NaN,NaN,NaN,3.000000
max,NaN,NaN,NaN,545749.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,inf,NaN,NaN,NaN,NaN,NaN,NaN,72.000000

In [21]:
df['Setor'].unique()

array(['Shoppings', 'Híbrido', 'Títulos e Val. Mob.',
       'Lajes Corporativas', 'Logística', 'Outros', nan, 'Residencial',
       'Hospital', 'Hotel'], dtype=object)

In [22]:
df.columns

Index(['Códigodo fundo', 'Setor', 'Preço Atual', 'Liquidez Diária',
       'Dividendo', 'DividendYield', 'DY (3M)Acumulado', 'DY (6M)Acumulado',
       'DY (12M)Acumulado', 'DY (3M)Média', 'DY (6M)Média', 'DY (12M)Média',
       'DY Ano', 'Variação Preço', 'Rentab.Período', 'Rentab.Acumulada',
       'PatrimônioLíq.', 'VPA', 'P/VPA', 'DYPatrimonial',
       'VariaçãoPatrimonial', 'Rentab. Patr.no Período',
       'Rentab. Patr.Acumulada', 'VacânciaFísica', 'VacânciaFinanceira',
       'QuantidadeAtivos'],
      dtype='object')

## 2. Limpeza e Formatação de Dados

In [23]:
df.isna().sum()

Códigodo fundo               0
Setor                        1
Preço Atual                  7
Liquidez Diária              7
Dividendo                    0
DividendYield               13
DY (3M)Acumulado            13
DY (6M)Acumulado            13
DY (12M)Acumulado           13
DY (3M)Média                13
DY (6M)Média                13
DY (12M)Média               13
DY Ano                      24
Variação Preço              13
Rentab.Período              13
Rentab.Acumulada            13
PatrimônioLíq.               0
VPA                          0
P/VPA                        7
DYPatrimonial              188
VariaçãoPatrimonial        188
Rentab. Patr.no Período    188
Rentab. Patr.Acumulada     188
VacânciaFísica             126
VacânciaFinanceira         218
QuantidadeAtivos             0
dtype: int64

### Dados categóricos

In [24]:
categorical_columns = ['Códigodo fundo','Setor']

In [27]:
idx = df[df['Setor'].isna()].index
df.drop(idx, inplace=True)

In [29]:
df[categorical_columns].isna().sum()

Códigodo fundo    0
Setor             0
dtype: int64

In [30]:
df[categorical_columns] = df[categorical_columns].astype('category')

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 243 entries, 137 to 133
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Códigodo fundo           243 non-null    category
 1   Setor                    243 non-null    category
 2   Preço Atual              237 non-null    object
 3   Liquidez Diária          237 non-null    float64
 4   Dividendo                243 non-null    object
 5   DividendYield            231 non-null    object
 6   DY (3M)Acumulado         231 non-null    object
 7   DY (6M)Acumulado         231 non-null    object
 8   DY (12M)Acumulado        231 non-null    object
 9   DY (3M)Média             231 non-null    object
 10  DY (6M)Média             231 non-null    object
 11  DY (12M)Média            231 non-null    object
 12  DY Ano                   220 non-null    object
 13  Variação Preço           231 non-null    object
 14  Rentab.Período           231 non-null    object
 15  Rentab.Acumulada         231 non-null    object
 16  PatrimônioLíq.           243 non-null    object
 17  VPA                      243 non-null    object
 18  P/VPA                    237 non-null    float64
 19  DYPatrimonial            56 non-null     object
 20  VariaçãoPatrimonial      56 non-null     object
 21  Rentab. Patr.no Período  56 non-null     object
 22  Rentab. Patr.Acumulada   56 non-null     object
 23  VacânciaFísica           118 non-null    object
 24  VacânciaFinanceira       26 non-null     object
 25  QuantidadeAtivos         243 non-null    int64
dtypes: category(2), float64(2), int64(1), object(21)
memory usage: 58.5+ KB

In [32]:
df.isna().sum()

Códigodo fundo               0
Setor                        0
Preço Atual                  6
Liquidez Diária              6
Dividendo                    0
DividendYield               12
DY (3M)Acumulado            12
DY (6M)Acumulado            12
DY (12M)Acumulado           12
DY (3M)Média                12
DY (6M)Média                12
DY (12M)Média               12
DY Ano                      23
Variação Preço              12
Rentab.Período              12
Rentab.Acumulada            12
PatrimônioLíq.               0
VPA                          0
P/VPA                        6
DYPatrimonial              187
VariaçãoPatrimonial        187
Rentab. Patr.no Período    187
Rentab. Patr.Acumulada     187
VacânciaFísica             125
VacânciaFinanceira         217
QuantidadeAtivos             0
dtype: int64

### Dados Numéricos

In [35]:
col_floats = list(df.iloc[:,2:-1].columns)

In [37]:
## Dados nulos
df[col_floats] = df[col_floats].fillna(value=0)

In [41]:
df[col_floats]

,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,DY (6M)Média,DY (12M)Média,...,Rentab.Acumulada,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira
137,"R$ 73,97",2654.0,"R$ 0,51","0,74%","1,27%","2,58%","0,00%","0,42%","0,43%","0,00%",...,"-9,06%","R$ 1.077.525.130,29","R$ 88,29",84.0,"0,44%","-0,05%","0,39%","1,48%","9,10%",0
129,"R$ 110,84",515.0,"R$ 1,55","1,40%","3,29%","5,94%","10,57%","1,10%","0,99%","0,88%",...,"2,38%","R$ 121.528.154,28","R$ 102,36",108.0,0,0,0,0,0,0
29,"R$ 106,75",5826.0,"R$ 8,76","8,76%","8,76%","8,76%","16,82%","2,92%","1,46%","1,40%",...,"17,52%","R$ 39.305.966,92","R$ 107,06",100.0,0,0,0,0,0,0
126,"R$ 80,60",4416.0,"R$ 0,57","0,69%","1,97%","3,81%","0,00%","0,66%","0,64%","0,00%",...,"-8,70%","R$ 483.257.233,98","R$ 100,16",80.0,0,0,0,0,"0,00%",0
3,"R$ 1.145,00",176.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%",...,"-28,29%","R$ 229.163.662,27","R$ 2.061,25",56.0,0,0,0,0,"68,15%",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49,"R$ 107,75",44998.0,"R$ 0,40","0,38%","0,81%","1,95%","3,56%","0,27%","0,32%","0,30%",...,"-5,05%","R$ 2.001.282.055,70","R$ 109,91",98.0,0,0,0,0,"5,90%",0
71,"R$ 68,70",14574.0,"R$ 0,48","0,73%","2,19%","4,17%","8,88%","0,73%","0,70%","0,74%",...,"-15,23%","R$ 627.324.285,79","R$ 85,74",80.0,0,0,0,0,"47,00%",0
171,"R$ 93,69",15014.0,"R$ 0,75","0,80%","2,50%","4,81%","9,28%","0,83%","0,80%","0,77%",...,"2,39%","R$ 401.337.388,51","R$ 92,68",101.0,0,0,0,0,0,0
2,"R$ 6,85",3560.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%",...,"-37,83%","R$ 25.862.448,60","R$ 13,97",49.0,0,0,0,0,"0,00%","100,00%"
133,0,0.0,"R$ 0,40","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%",...,"0,00%","R$ 37.614.094,39","R$ 95,19",0.0,"0,18%","0,23%","0,41%","0,41%",0,0

In [42]:
df[col_floats].head()

,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,DY (6M)Média,DY (12M)Média,...,Rentab.Acumulada,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira
137,"R$ 73,97",2654.0,"R$ 0,51","0,74%","1,27%","2,58%","0,00%","0,42%","0,43%","0,00%",...,"-9,06%","R$ 1.077.525.130,29","R$ 88,29",84.0,"0,44%","-0,05%","0,39%","1,48%","9,10%",0
129,"R$ 110,84",515.0,"R$ 1,55","1,40%","3,29%","5,94%","10,57%","1,10%","0,99%","0,88%",...,"2,38%","R$ 121.528.154,28","R$ 102,36",108.0,0,0,0,0,0,0
29,"R$ 106,75",5826.0,"R$ 8,76","8,76%","8,76%","8,76%","16,82%","2,92%","1,46%","1,40%",...,"17,52%","R$ 39.305.966,92","R$ 107,06",100.0,0,0,0,0,0,0
126,"R$ 80,60",4416.0,"R$ 0,57","0,69%","1,97%","3,81%","0,00%","0,66%","0,64%","0,00%",...,"-8,70%","R$ 483.257.233,98","R$ 100,16",80.0,0,0,0,0,"0,00%",0
3,"R$ 1.145,00",176.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%",...,"-28,29%","R$ 229.163.662,27","R$ 2.061,25",56.0,0,0,0,0,"68,15%",0

In [48]:
df[col_floats] = df[col_floats].applymap(lambda x: str(x).replace('R$', '').replace('.0','').replace('.','').replace('%','').replace(',','.'))

In [49]:
df[col_floats] = df[col_floats].astype('float')

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 243 entries, 137 to 133
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Códigodo fundo           243 non-null    category
 1   Setor                    243 non-null    category
 2   Preço Atual              243 non-null    float64
 3   Liquidez Diária          243 non-null    float64
 4   Dividendo                243 non-null    float64
 5   DividendYield            243 non-null    float64
 6   DY (3M)Acumulado         243 non-null    float64
 7   DY (6M)Acumulado         243 non-null    float64
 8   DY (12M)Acumulado        243 non-null    float64
 9   DY (3M)Média             243 non-null    float64
 10  DY (6M)Média             243 non-null    float64
 11  DY (12M)Média            243 non-null    float64
 12  DY Ano                   243 non-null    float64
 13  Variação Preço           243 non-null    float64
 14  Rentab.Período           243 non-null    float64
 15  Rentab.Acumulada         243 non-null    float64
 16  PatrimônioLíq.           243 non-null    float64
 17  VPA                      243 non-null    float64
 18  P/VPA                    243 non-null    float64
 19  DYPatrimonial            243 non-null    float64
 20  VariaçãoPatrimonial      243 non-null    float64
 21  Rentab. Patr.no Período  243 non-null    float64
 22  Rentab. Patr.Acumulada   243 non-null    float64
 23  VacânciaFísica           243 non-null    float64
 24  VacânciaFinanceira       243 non-null    float64
 25  QuantidadeAtivos         243 non-null    int64
dtypes: category(2), float64(23), int64(1)
memory usage: 58.5 KB

In [51]:
df.head()

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
137,ABCP11,Shoppings,73.97,2654.0,0.51,0.74,1.27,2.58,0.00,0.42,...,1.775251e+08,88.29,84.0,0.44,-0.05,0.39,1.48,9.10,0.0,1
129,AFCR11,Híbrido,110.84,515.0,1.55,1.40,3.29,5.94,10.57,1.10,...,1.215282e+08,102.36,108.0,0.00,0.00,0.00,0.00,0.00,0.0,0
29,AFOF11,Títulos e Val. Mob.,106.75,5826.0,8.76,8.76,8.76,8.76,16.82,2.92,...,3.930597e+07,107.06,100.0,0.00,0.00,0.00,0.00,0.00,0.0,0
126,AIEC11,Lajes Corporativas,80.60,4416.0,0.57,0.69,1.97,3.81,0.00,0.66,...,4.832572e+08,100.16,80.0,0.00,0.00,0.00,0.00,0.00,0.0,2
3,ALMI11,Lajes Corporativas,1145.00,176.0,0.00,0.00,0.00,0.00,0.00,0.00,...,2.291637e+08,261.25,56.0,0.00,0.00,0.00,0.00,68.15,0.0,1

In [52]:
df.describe()

,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,DY (6M)Média,DY (12M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
count,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,...,2.430000e+02,243.000000,243.0,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000
mean,467.841852,15280.456790,5.390000,1.039959,2.116008,3.418395,5.406461,0.705432,0.569630,0.450453,...,4.057168e+08,597.471152,inf,0.154198,0.049588,0.204074,0.588601,7.384486,1.310288,3.353909
std,5110.572838,44998.023384,59.116933,3.403459,3.546429,4.139285,5.860466,1.182217,0.689965,0.488266,...,6.300817e+08,5744.776012,NaN,0.316948,0.732803,0.841465,2.339812,17.740402,8.271709,7.944426
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-6.281734e+06,-8.280000,-155.0,0.000000,-2.540000,-1.860000,-9.350000,0.000000,0.000000,0.000000
25%,79.645000,215.000000,0.415000,0.425000,1.065000,1.045000,0.000000,0.355000,0.175000,0.000000,...,4.817601e+07,92.490000,83.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,97.000000,3195.000000,0.650000,0.670000,1.830000,3.340000,5.800000,0.610000,0.560000,0.480000,...,1.659057e+08,99.870000,95.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,109.800000,14237.000000,0.985000,0.820000,2.385000,4.420000,8.120000,0.795000,0.740000,0.680000,...,4.734209e+08,109.645000,102.0,0.000000,0.000000,0.000000,0.000000,5.350000,0.000000,3.000000
max,79700.050000,545749.000000,919.210000,36.320000,37.990000,40.960000,45.220000,12.660000,6.830000,3.770000,...,3.850279e+09,87737.000000,inf,1.250000,6.960000,7.510000,25.620000,100.000000,100.000000,72.000000

- Dados de P/VPA tem atributos infinitos e está em uma escala diferente

In [53]:
## Check infinity values pandas
df[np.isinf(df[col_floats]).any(1)]

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
7,RBCB11,Outros,19.0,161.0,0.0,0.0,0.29,4.38,14.62,0.1,...,0.0,0.0,inf,0.0,0.0,0.0,0.0,0.0,0.0,0

In [54]:
idx = df[np.isinf(df[col_floats]).any(1)].index
df.drop(idx, inplace=True)

In [58]:
df['P/VPA'] = df['P/VPA']/100

In [59]:
df.describe()

,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,DY (6M)Média,DY (12M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
count,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000,...,2.420000e+02,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000
mean,469.696570,15342.933884,5.412273,1.044256,2.123554,3.414421,5.368388,0.707934,0.568967,0.447273,...,4.073933e+08,599.940041,0.907975,0.154835,0.049793,0.204917,0.591033,7.415000,1.315702,3.367769
std,5121.082757,45080.720946,59.238433,3.409852,3.551824,4.147399,5.842421,1.184023,0.691318,0.486750,...,6.308442e+08,5756.553112,0.351794,0.317449,0.734315,0.843106,2.344353,17.770778,8.288421,7.957947
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-6.281734e+06,-8.280000,-1.550000,0.000000,-2.540000,-1.860000,-9.350000,0.000000,0.000000,0.000000
25%,80.150000,235.000000,0.420000,0.432500,1.080000,0.977500,0.000000,0.360000,0.162500,0.000000,...,5.034971e+07,92.537500,0.830000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,97.050000,3195.500000,0.650000,0.670000,1.835000,3.335000,5.770000,0.610000,0.560000,0.480000,...,1.667646e+08,99.895000,0.950000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,110.205000,14251.000000,0.992500,0.825000,2.387500,4.420000,8.110000,0.797500,0.740000,0.680000,...,4.742794e+08,109.777500,1.020000,0.000000,0.000000,0.000000,0.000000,5.375000,0.000000,3.000000
max,79700.050000,545749.000000,919.210000,36.320000,37.990000,40.960000,45.220000,12.660000,6.830000,3.770000,...,3.850279e+09,87737.000000,4.040000,1.250000,6.960000,7.510000,25.620000,100.000000,100.000000,72.000000

### Analisando a média por setor

In [60]:
df.columns

Index(['Códigodo fundo', 'Setor', 'Preço Atual', 'Liquidez Diária',
       'Dividendo', 'DividendYield', 'DY (3M)Acumulado', 'DY (6M)Acumulado',
       'DY (12M)Acumulado', 'DY (3M)Média', 'DY (6M)Média', 'DY (12M)Média',
       'DY Ano', 'Variação Preço', 'Rentab.Período', 'Rentab.Acumulada',
       'PatrimônioLíq.', 'VPA', 'P/VPA', 'DYPatrimonial',
       'VariaçãoPatrimonial', 'Rentab. Patr.no Período',
       'Rentab. Patr.Acumulada', 'VacânciaFísica', 'VacânciaFinanceira',
       'QuantidadeAtivos'],
      dtype='object')

In [61]:
indicadores = ['Códigodo fundo',
               'Setor', 
               'DY (12M)Acumulado', 
               'VacânciaFísica', 
               'VacânciaFinanceira', 
               'P/VPA', 
               'QuantidadeAtivos', 
               'Liquidez Diária']

In [62]:
df_aux = df[indicadores]

In [63]:
df_aux

,Códigodo fundo,Setor,DY (12M)Acumulado,VacânciaFísica,VacânciaFinanceira,P/VPA,QuantidadeAtivos,Liquidez Diária
137,ABCP11,Shoppings,0.00,9.10,0.0,0.84,1,2654.0
129,AFCR11,Híbrido,10.57,0.00,0.0,1.08,0,515.0
29,AFOF11,Títulos e Val. Mob.,16.82,0.00,0.0,1.00,0,5826.0
126,AIEC11,Lajes Corporativas,0.00,0.00,0.0,0.80,2,4416.0
3,ALMI11,Lajes Corporativas,0.00,68.15,0.0,0.56,1,176.0
...,...,...,...,...,...,...,...,...
49,XPML11,Shoppings,3.56,5.90,0.0,0.98,13,44998.0
71,XPPR11,Outros,8.88,47.00,0.0,0.80,4,14574.0
171,XPSF11,Outros,9.28,0.00,0.0,1.01,0,15014.0
2,XTED11,Lajes Corporativas,0.00,0.00,100.0,0.49,1,3560.0
133,YUFI11B,Residencial,0.00,0.00,0.0,0.00,0,0.0

In [64]:
media_setor = df_aux.groupby('Setor').agg(['mean','std'])

In [65]:
media_setor

                    DY (12M)Acumulado            VacânciaFísica             \
                                 mean        std           mean        std
Setor
Hospital                     5.030000   4.530530       0.000000   0.000000
Hotel                        4.270000   3.829452      53.866667  46.656761
Híbrido                      4.390526   4.590571       3.865000   8.570495
Lajes Corporativas           6.211282   7.093434      26.343590  29.435617
Logística                    4.768000   2.913261       5.505000  13.695004
Outros                       6.061143   5.182761       2.082857   8.197363
Residencial                  6.377500  15.825424       4.262500  10.857905
Shoppings                    1.540455   1.991569      10.975455  11.653826
Títulos e Val. Mob.          6.348108   5.311715       0.000000   0.000000

                    VacânciaFinanceira                P/VPA            \
                                  mean        std      mean       std
Setor
Hospital                      0.000000   0.000000  1.193333  0.160104
Hotel                         0.000000   0.000000  0.916667  0.102144
Híbrido                       1.267895   3.838064  0.810000  0.464048
Lajes Corporativas            4.621026  17.139423  0.879744  0.573886
Logística                     4.045000  14.496224  0.975000  0.137286
Outros                        0.260000   1.225273  0.894286  0.327569
Residencial                   0.000000   0.000000  0.996250  0.558491
Shoppings                     0.000000   0.000000  0.764545  0.188218
Títulos e Val. Mob.           0.000000   0.000000  0.982703  0.095978

                    QuantidadeAtivos            Liquidez Diária
                                mean        std            mean            std
Setor
Hospital                    1.000000   0.000000      316.000000     431.447563
Hotel                       9.333333  12.096832      482.333333     751.466788
Híbrido                     3.736842   5.011793    31270.789474  103635.709337
Lajes Corporativas          4.205128  10.513599     4479.666667    8120.062984
Logística                   7.650000   5.382965    13766.250000   15651.514226
Outros                      6.342857  14.356681    16073.285714   26320.257809
Residencial                 0.750000   1.488048     2251.875000    4948.055937
Shoppings                   4.272727   5.063236     8913.409091   14301.492202
Títulos e Val. Mob.         0.040541   0.198569    17508.081081   23091.171134

In [68]:
media_setor.loc['Residencial', ('DY (12M)Acumulado', 'mean')]

6.3774999999999995

### Criando uma função com uma estratégia para oportunidades do mercado

In [76]:
def oportunidade_media_setor(df, setor='Shoppings', label_setor='Setor'):
    
    media_setor = df_aux.groupby('Setor').agg(['mean','std'])
    
    df_setor = df[df[label_setor].isin([setor])]
    
    filter_ = \
            (df_setor['QuantidadeAtivos'] > 5) &\
            (df_setor['Liquidez Diária'] > 5000) &\
            (df_setor['P/VPA'] < 1.0) &\
            (df_setor['DY (12M)Acumulado'] > media_setor.loc[setor, ('DY (12M)Acumulado','mean')]) 
            
    print('média do setor Yield: {}'.format(media_setor.loc[setor, ('DY (12M)Acumulado','mean')]))
    print('média do setor p/VPA: {}'.format(media_setor.loc[setor, ('P/VPA','mean')]))
    print('média do setor Ativos: {}'.format(media_setor.loc[setor, ('QuantidadeAtivos','mean')]))
    
    return df_setor[filter_]

In [77]:
list(df['Setor'].unique())

['Shoppings',
 'Híbrido',
 'Títulos e Val. Mob.',
 'Lajes Corporativas',
 'Logística',
 'Outros',
 'Residencial',
 'Hospital',
 'Hotel']

In [78]:
oportunidade = oportunidade_media_setor(df_aux, setor='Logística')
oportunidade.sort_values('DY (12M)Acumulado', ascending=False, inplace=True)
oportunidade

média do setor Yield: 4.768
média do setor p/VPA: 0.975
média do setor Ativos: 7.65

,Códigodo fundo,Setor,DY (12M)Acumulado,VacânciaFísica,VacânciaFinanceira,P/VPA,QuantidadeAtivos,Liquidez Diária
204,RBRL11,Logística,7.48,0.0,0.0,0.99,7,10608.0
190,GGRC11,Logística,6.50,0.0,0.0,0.99,15,13350.0
73,LVBI11,Logística,5.43,1.0,0.0,0.95,9,22037.0