# Coletando dados de ações do mercado financeiro

## Yahoo Finance

In [2]:
#!pip install yfinance
import yfinance as yf
from pandas import json_normalize
import pandas as pd

###### Criando um Ticker

In [18]:
ticker = yf.Ticker('BBAS3.SA') #"MSFT", ^BVSP, USDBRL=X BTC-USD

###### Cotações

In [19]:
ticker.history(period='1y', interval='1d')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2020-05-04,26.149300,26.521906,25.786247,26.521906,16586000,0.0,0
2020-05-05,26.770315,27.276676,26.330830,26.560125,15799600,0.0,0
2020-05-06,26.712987,26.875405,25.556953,25.786249,20312700,0.0,0
2020-05-07,26.216181,26.225735,24.907282,25.088808,26405900,0.0,0
2020-05-08,25.891342,26.474135,25.604721,25.891342,17576000,0.0,0
...,...,...,...,...,...,...,...
2021-04-28,29.990000,30.370001,29.850000,30.299999,15213600,0.0,0
2021-04-29,30.299999,30.520000,29.570000,29.639999,14692400,0.0,0
2021-04-30,29.670000,29.850000,29.440001,29.639999,12656100,0.0,0
2021-05-03,29.820000,30.030001,29.549999,29.770000,9153600,0.0,0
2021-05-04,29.900000,29.969999,29.190001,29.370001,12156900,0.0,0

###### Balanço Patrimonial anual

In [24]:
ticker.balance_sheet

,2020-12-31,2019-12-31,2018-12-31,2017-12-31
Intangible Assets,6.220666e+09,5.920549e+09,5.782032e+09,6.926729e+09
Total Liab,1.598701e+12,1.372530e+12,1.314649e+12,1.270478e+12
Total Stockholder Equity,1.245677e+11,1.066612e+11,9.974197e+10,9.532573e+10
Minority Interest,2.403457e+09,1.903656e+09,2.510915e+09,3.397672e+09
Other Current Liab,5.410652e+10,5.015906e+10,9.600237e+10,8.549135e+10
Total Assets,1.725672e+12,1.481095e+12,1.416901e+12,1.369201e+12
Common Stock,9.000002e+10,6.700000e+10,6.700000e+10,6.700000e+10
Other Current Assets,1.369531e+11,1.372411e+11,6.577648e+10,9.496479e+10
Retained Earnings,3.919847e+10,5.381466e+10,4.261258e+10,3.528069e+10
Other Liab,1.305880e+11,1.129271e+11,2.403604e+10,2.516772e+10
Treasury Stock,-4.630839e+09,-1.415342e+10,-9.870615e+09,-6.954961e+09
Other Assets,7.148683e+11,6.543640e+11,6.673905e+11,6.759390e+11
Cash,1.761895e+11,7.193602e+10,3.818834e+10,3.560214e+10
Total Current Liabilities,1.278059e+12,1.063533e+12,1.082949e+12,1.051245e+12
Deferred Long Term Asset Charges,5.814258e+10,5.946293e+10,NaN,NaN
Short Long Term Debt,5.880469e+11,4.898459e+11,4.925471e+11,5.042522e+11
Other Stockholder Equity,-4.350197e+09,-1.381378e+10,-8.037184e+09,-5.104918e+09
Property Plant Equipment,8.230854e+09,7.882695e+09,7.537617e+09,7.415302e+09
Total Current Assets,3.484755e+11,2.302539e+11,6.071002e+11,5.531098e+11
Long Term Investments,6.478766e+11,5.826741e+11,1.290911e+11,1.258103e+11
Net Tangible Assets,1.183470e+11,1.007407e+11,9.395994e+10,8.839900e+10
Short Term Investments,7.315580e+08,2.065050e+08,4.281338e+11,3.821750e+11
Net Receivables,1.336690e+10,1.444640e+10,7.407338e+10,3.953169e+10
Long Term Debt,1.900535e+11,1.960705e+11,2.076640e+11,1.940653e+11
Accounts Payable,6.334196e+11,5.187375e+11,4.860368e+11,4.502294e+11
Inventory,NaN,NaN,6.098800e+07,5.623500e+07

###### Balanço Patrimonial Trimestral

In [25]:
ticker.quarterly_balance_sheet

,2020-12-31,2020-09-30,2020-06-30,2020-03-31
Intangible Assets,6.220666e+09,6.366255e+09,6.896055e+09,6.580505e+09
Total Liab,1.598701e+12,1.647590e+12,1.595398e+12,1.467875e+12
Total Stockholder Equity,1.245677e+11,1.199186e+11,1.128099e+11,1.099949e+11
Minority Interest,2.403457e+09,2.415103e+09,2.026446e+09,2.320385e+09
Other Current Liab,5.410652e+10,5.645059e+10,5.268821e+10,1.165273e+11
Total Assets,1.725672e+12,1.769923e+12,1.710234e+12,1.580190e+12
Common Stock,9.000002e+10,9.000000e+10,6.700000e+10,6.700000e+10
Other Current Assets,1.369531e+11,1.428031e+11,1.464974e+11,9.202280e+10
Retained Earnings,3.919847e+10,3.762960e+10,5.841287e+10,5.648046e+10
Other Liab,1.305880e+11,1.274683e+11,1.369143e+11,3.877309e+10
Treasury Stock,-4.630839e+09,-7.711041e+09,-1.260299e+10,-1.348552e+10
Other Assets,7.148683e+11,6.999928e+11,6.918273e+11,6.250512e+11
Cash,1.761895e+11,7.789134e+10,8.115539e+10,4.562298e+10
Total Current Liabilities,1.278059e+12,1.314441e+12,1.251331e+12,1.218374e+12
Deferred Long Term Asset Charges,5.814258e+10,6.010949e+10,6.271350e+10,NaN
Short Long Term Debt,5.880469e+11,6.513166e+11,6.054860e+11,5.639742e+11
Other Stockholder Equity,-4.350197e+09,-7.430335e+09,-1.229771e+10,-1.318021e+10
Property Plant Equipment,8.230854e+09,7.925262e+09,7.972408e+09,7.719945e+09
Total Current Assets,3.484755e+11,7.991924e+11,7.370415e+11,8.164038e+11
Long Term Investments,6.478766e+11,2.564465e+11,2.664967e+11,1.244349e+11
Net Tangible Assets,1.183470e+11,1.135523e+11,1.059138e+11,1.034144e+11
Short Term Investments,7.315580e+08,5.374247e+11,4.666445e+11,5.492726e+11
Net Receivables,1.336690e+10,1.461691e+10,1.618670e+10,1.232749e+11
Long Term Debt,1.900535e+11,2.056806e+11,2.071521e+11,2.107280e+11
Accounts Payable,6.334196e+11,6.055115e+11,5.931571e+11,5.368101e+11
Inventory,NaN,NaN,NaN,6.245300e+07

###### Fluxo de Caixa anual

In [26]:
ticker.cashflow

,2020-12-31,2019-12-31,2018-12-31,2017-12-31
Investments,-9.416455e+10,-2.728768e+10,-1.153321e+10,-1.538465e+10
Change To Liabilities,0.000000e+00,0.000000e+00,2.662160e+08,8.200310e+08
Total Cashflows From Investing Activities,-9.564641e+10,-3.013845e+10,-1.059416e+10,-1.447812e+10
Net Borrowings,-1.278763e+10,-7.284291e+09,-3.097480e+09,1.720000e+09
Total Cash From Financing Activities,1.011075e+11,1.918133e+10,2.679381e+10,3.534301e+09
Change To Operating Activities,4.105831e+10,-4.258229e+09,-4.313130e+10,-8.495338e+10
Issuance Of Stock,1.526800e+07,2.805364e+09,1.661200e+07,4.706000e+06
Net Income,1.269738e+10,1.816207e+10,1.286203e+10,1.101078e+10
Change In Cash,1.042535e+11,1.160057e+10,1.315150e+10,-5.593972e+10
Effect Of Exchange Rate,1.032067e+10,-1.587850e+08,2.522422e+09,3.614600e+07
Total Cash From Operating Activities,8.847173e+10,2.271647e+10,-5.570568e+09,-4.503204e+10
Depreciation,2.762620e+09,3.036181e+09,3.157990e+09,4.456598e+09
Other Cashflows From Investing Activities,2.265323e+09,1.473059e+09,2.925249e+09,3.219813e+09
Dividends Paid,-2.404018e+09,-2.451730e+09,-1.706455e+09,-2.623783e+09
Other Cashflows From Financing Activities,1.180794e+11,3.078126e+10,3.408120e+10,4.433378e+09
Change To Netincome,3.322187e+10,2.724141e+10,2.276248e+10,2.847375e+10
Capital Expenditures,-1.700104e+09,-1.651586e+09,-1.361242e+09,-1.020391e+09

###### Fluxo de Caixa Trimestral

In [27]:
ticker.quarterly_cashflow

,2020-12-31,2020-09-30,2020-06-30,2020-03-31
Investments,-4.206059e+10,1.010226e+09,-6.147968e+10,8.365488e+09
Change To Liabilities,0.000000e+00,0.000000e+00,7.360000e+05,-7.360000e+05
Total Cashflows From Investing Activities,-4.264485e+10,1.451048e+09,-6.192076e+10,7.468157e+09
Net Borrowings,-5.828426e+09,-1.032453e+09,-1.400006e+10,8.073314e+09
Total Cash From Financing Activities,2.792613e+10,1.277831e+10,3.855944e+10,2.184362e+10
Change To Operating Activities,1.067268e+11,-4.137604e+10,3.982240e+09,-2.827466e+10
Net Income,3.199054e+09,3.084902e+09,3.208748e+09,3.204681e+09
Change In Cash,9.829817e+10,-3.264048e+09,-1.797224e+10,2.719161e+10
Effect Of Exchange Rate,-3.759054e+09,6.231200e+08,5.078782e+09,8.377820e+09
Total Cash From Operating Activities,1.167759e+11,-1.811652e+10,3.103020e+08,-1.049799e+10
Depreciation,7.102640e+08,7.093000e+08,6.639800e+08,6.790760e+08
Other Cashflows From Investing Activities,4.226660e+08,6.544890e+08,8.678950e+08,3.202730e+08
Other Cashflows From Financing Activities,3.555012e+10,1.536086e+10,5.255950e+10,1.551499e+10
Change To Netincome,3.753609e+09,8.109767e+09,8.619080e+09,1.273941e+10
Capital Expenditures,-6.138230e+08,-3.453670e+08,-5.666590e+08,-1.742550e+08
Dividends Paid,NaN,-1.550105e+09,-1.550105e+09,-1.759951e+09
Issuance Of Stock,NaN,NaN,NaN,1.526800e+07

###### Financeiro anual

In [29]:
ticker.financials

,2020-12-31,2019-12-31,2018-12-31,2017-12-31
Research Development,None,None,None,None
Effect Of Accounting Charges,None,None,None,None
Income Before Tax,1.2821e+10,1.37834e+10,1.90252e+10,1.67117e+10
Minority Interest,2.40346e+09,1.90366e+09,2.51092e+09,3.39767e+09
Net Income,1.26974e+10,1.81621e+10,1.2862e+10,1.10108e+10
Selling General Administrative,3.40472e+10,3.48473e+10,3.32618e+10,3.42098e+10
Gross Profit,5.77461e+10,6.10117e+10,5.96184e+10,5.73988e+10
Ebit,0,0,0,0
Operating Income,1.36218e+10,1.70365e+10,2.03122e+10,1.65838e+10
Other Operating Expenses,1.00771e+10,9.12783e+09,6.04446e+09,6.60522e+09
Interest Expense,None,None,None,None
Extraordinary Items,None,None,None,None
Non Recurring,None,None,None,None
Other Items,None,None,None,None
Income Tax Expense,-1.45286e+09,-6.8605e+09,4.76737e+09,4.05086e+09
Total Revenue,5.84832e+10,6.17459e+10,6.03344e+10,5.81058e+10
Total Operating Expenses,4.48614e+10,4.47093e+10,4.00222e+10,4.1522e+10
Cost Of Revenue,7.37076e+08,7.34209e+08,7.15937e+08,7.06984e+08
Total Other Income Expense Net,-8.00745e+08,-3.25309e+09,-1.28694e+09,1.2788e+08
Discontinued Operations,None,None,None,None
Net Income From Continuing Ops,1.42739e+10,2.06439e+10,1.42579e+10,1.26608e+10
Net Income Applicable To Common Shares,1.25122e+10,1.78993e+10,1.26488e+10,1.08811e+10

###### Financeiro Trimestral

In [30]:
ticker.quarterly_financials

,2020-12-31,2020-09-30,2020-06-30,2020-03-31
Research Development,None,None,None,None
Effect Of Accounting Charges,None,None,None,None
Income Before Tax,4.09066e+09,3.6267e+09,3.75554e+09,1.34814e+09
Minority Interest,2.40346e+09,2.4151e+09,2.02645e+09,2.32038e+09
Net Income,3.19905e+09,3.0849e+09,3.20875e+09,3.20468e+09
Selling General Administrative,8.64576e+09,8.61449e+09,8.42615e+09,8.36081e+09
Gross Profit,1.69122e+10,1.46639e+10,1.43829e+10,1.17871e+10
Ebit,0,0,0,0
Operating Income,4.64876e+09,3.75639e+09,3.63129e+09,1.58535e+09
Other Operating Expenses,3.61773e+09,2.29301e+09,2.32546e+09,1.8409e+09
Interest Expense,None,None,None,None
Extraordinary Items,None,None,None,None
Non Recurring,None,None,None,None
Other Items,None,None,None,None
Income Tax Expense,5.19266e+08,1.03634e+08,1.31115e+08,-2.20688e+09
Total Revenue,1.71029e+10,1.48426e+10,1.45643e+10,1.19734e+10
Total Operating Expenses,1.24541e+10,1.10862e+10,1.0933e+10,1.0388e+10
Cost Of Revenue,1.90614e+08,1.78731e+08,1.81424e+08,1.86307e+08
Total Other Income Expense Net,-5.58097e+08,-1.29689e+08,1.24249e+08,-2.37208e+08
Discontinued Operations,None,None,None,None
Net Income From Continuing Ops,3.5714e+09,3.52307e+09,3.62442e+09,3.55502e+09
Net Income Applicable To Common Shares,3.12682e+09,3.03748e+09,3.15858e+09,3.18928e+09

###### Informações e Estatística

In [33]:
ticker.get_info()['lastDividendDate']

1615507200

In [34]:
info = json_normalize(ticker.get_info())

In [35]:
info.head()

,sector,fullTimeEmployees,longBusinessSummary,city,state,country,companyOfficers,website,maxAge,address1,...,dateShortInterest,pegRatio,lastCapGain,shortPercentOfFloat,sharesShortPriorMonth,impliedSharesOutstanding,category,fiveYearAverageReturn,regularMarketPrice,logo_url
0,Financial Services,91673,Banco do Brasil S.A. provides banking products...,BrasÃ­lia,DF,Brazil,[],http://www.bb.com.br,1,Setor de Autarquias Norte,...,None,None,None,None,None,None,None,None,29.37,https://logo.clearbit.com/bb.com.br

In [37]:
len(info.columns)

122

In [44]:
selected = [c for c in list(info.columns) if 'beta' in c] #PE, Dividend, beta

In [45]:
selected

['beta', 'beta3Year']

In [46]:
info[selected]

       beta beta3Year
0  1.069438      None

###### Detentores de fundo mútuo

In [47]:
ticker.get_institutional_holders()

,Holder,Shares,Date Reported,% Out,Value
0,Fidelity Series Emerging Markets Opportunities...,18411038,2021-02-27,0.0064,516429615
1,iShares MSCI Brazil ETF,15391287,2021-03-30,0.0054,468664689
2,Lazard Emerging Markets Equity Portfolio,11825926,2020-12-30,0.0041,458845928
3,Vanguard International Stock Index-Emerging Ma...,11823037,2021-01-30,0.0041,400328032
4,Vanguard International Stock Index-Total Intl ...,11803398,2021-01-30,0.0041,399663056
5,iShares Core MSCI Emerging Markets ETF,7251713,2021-03-30,0.0025,220814660
6,iShares Latin America 40 ETF,6206900,2021-03-30,0.0022,189000105
7,Blackrock Ser Inc-Blackrock International Fund,4209764,2021-02-27,0.0015,118083880
8,Nuveen Investment Trust II - International Gro...,3915700,2021-03-30,0.0014,119233065
9,DFA Investment Dimensions-DFA Emerging Mkts Value,3882886,2021-01-30,0.0014,131474519

In [49]:
ticker.get_mutualfund_holders()

###### Distribuição acionária

In [48]:
ticker.get_major_holders()

        0                                      1
0  50.00%        % of Shares Held by All Insider
1  20.15%       % of Shares Held by Institutions
2  40.31%        % of Float Held by Institutions
3     451  Number of Institutions Holding Shares